version: '3'
services:
  linux01:
    image: chenchongbiao/spark:v1
    working_dir: /usr/local/spark
    container_name: linux01
    hostname: linux01
    volumes:
      - ../hadoop/cluster/conf/core-site.xml:/usr/local/hadoop/etc/hadoop/core-site.xml
      - ../hadoop/cluster/conf/hdfs-site.xml:/usr/local/hadoop/etc/hadoop/hdfs-site.xml
      - ../hadoop/cluster/conf/hadoop-env.sh:/usr/local/hadoop/etc/hadoop/hadoop-env.sh
      - ../hadoop/cluster/conf/workers:/usr/local/hadoop/etc/hadoop/workers
      - ../hadoop/sbin:/usr/local/hadoop/sbin
      - ./cluster/conf:/usr/local/spark/conf
      - ./maven/conf/settings.xml:/usr/local/maven/conf/settings.xml
    ports:
      - "4040:4040"
      - "8080:8080"
      - "9870:9870"
      - "16010:16010"
    restart: always
  linux02:
    image: chenchongbiao/spark:v1
    working_dir: /usr/local/spark
    container_name: linux02
    hostname: linux02
    volumes:
      - ../hadoop/cluster/conf/core-site.xml:/usr/local/hadoop/etc/hadoop/core-site.xml
      - ../hadoop/cluster/conf/hdfs-site.xml:/usr/local/hadoop/etc/hadoop/hdfs-site.xml
      - ../hadoop/cluster/conf/hadoop-env.sh:/usr/local/hadoop/etc/hadoop/hadoop-env.sh
      - ../hadoop/cluster/conf/workers:/usr/local/hadoop/etc/hadoop/workers
      - ../hadoop/sbin:/usr/local/hadoop/sbin
      - ./cluster/conf:/usr/local/spark/conf
    restart: always
    links:
      - linux01
  linux03:
    image: chenchongbiao/spark:v1
    working_dir: /usr/local/spark
    container_name: linux03
    hostname: linux03
    volumes:
      - ../hadoop/cluster/conf/core-site.xml:/usr/local/hadoop/etc/hadoop/core-site.xml
      - ../hadoop/cluster/conf/hdfs-site.xml:/usr/local/hadoop/etc/hadoop/hdfs-site.xml
      - ../hadoop/cluster/conf/hadoop-env.sh:/usr/local/hadoop/etc/hadoop/hadoop-env.sh
      - ../hadoop/cluster/conf/workers:/usr/local/hadoop/etc/hadoop/workers
      - ../hadoop/sbin:/usr/local/hadoop/sbin
      - ./cluster/conf:/usr/local/spark/conf
    restart: always
    links:
      - linux01